Add new flags system
criteo/command-launcher pull request #111
Opened 2023-02-21 18:43 UTC by bhou

- new command configurations: flags, exclusiveFlags, groupFlags
- new command environment variable: [APPNAME]_NARGS, which returns the number of arguments

2023-02-22 11:44 UTC, gmonceyron requested changes

2023-02-22 11:44 UTC, gmonceyron commented on internal/frontend/default-frontend.go
> +		// deperacted
```suggestion
		// deprecated
```

2023-02-22 11:44 UTC, gmonceyron commented on internal/frontend/default-frontend.go
> +// return envrionment variable list, env variable table, original args including flags
```suggestion
// return environment variable list, env variable table, original args including flags
```

2023-02-22 11:44 UTC, gmonceyron commented on test/packages-src/flag-env/manifest.mf
> +      "short": "a commands to test flags",
```suggestion
      "short": "a command to test flags",
```

2023-02-22 11:44 UTC, gmonceyron commented on test/integration/test-flag-arg.sh
> +echo "$RESULT" | grep -q "\-\-json \-\-language fr \-\-name Joe World"
Shouldn't this also print `--isolated-required value`?

2023-02-23 15:31 UTC, bhou commented on test/integration/test-flag-arg.sh
> +echo "$RESULT" | grep -q "\-\-json \-\-language fr \-\-name Joe World"
Yes, you are right, I should include it in the test.

2023-02-24 09:52 UTC, gmonceyron approved these changes

2023-02-24 09:53 UTC, merged